version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/solkey
      - JWT_SECRET=your_jwt_secret_key_here
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - CLIENT_URL=http://localhost:3001
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    networks:
      - solkey-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - solkey-network

networks:
  solkey-network:
    driver: bridge

volumes:
  mongodb_data: