FROM mongo:6

# Copy keyfile and set permissions
COPY mongodb-keyfile /mongodb-keyfile
RUN chown mongodb:mongodb /mongodb-keyfile && chmod 600 /mongodb-keyfile

# Switch back to mongodb user
USER mongodb

# Start MongoDB with replica set and auth enabled
CMD ["mongod", "--auth", "--replSet", "rs0", "--keyFile", "/mongodb-keyfile", "--bind_ip_all"]