version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: pnpm dev
    networks:
      - solkey-network

networks:
  solkey-network:
    name: solkey-network
    external: false
