version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=solkey
      - MONGO_INITDB_ROOT_USERNAME=solkey_user
      - MONGO_INITDB_ROOT_PASSWORD=solkey_password
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./solkey-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://solkey_user:solkey_password@mongodb:27017/solkey?authSource=solkey
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key-here
      - PORT=3000
      - SOLANA_NETWORK=devnet
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./solkey-backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./mock-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./mock-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongodb_data:
